# Generated by Django 5.1.2 on 2024-12-08 22:10

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='schedule',
        ),
        migrations.AddField(
            model_name='jobs',
            name='work_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятница'), ('СБ', 'Суббота'), ('ВС', 'Воскресенье')], max_length=2), blank=True, default=list, help_text='Выберите дни работы', size=None),
        ),
        migrations.AddField(
            model_name='jobs',
            name='work_hours_duration',
            field=models.IntegerField(default=8, help_text='Длительность смены в часах'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='work_hours_start',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Время начала работы'),
        ),
    ]
